services:
  postgres:
    image: postgres:17
    container_name: nestjs-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nestjs-teacoder
    ports:
      - "15432:5432" # map container's 5432 to host's 15432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
